name: Build || Fetch aria2 Binaries

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "0 21 * * 6"  # 09:00 PM UTC Every Saturday --> 02:45 AM Nepal Time Every Sunday
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:        
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: main
          
      - name: Setup Env
        run: |
          # Create Output Dir
          mkdir -p "$GITHUB_WORKSPACE/main/aria2"

    #   - name: Build --> linux-x86-64-gcc 
    #     run: | 
    #       # git clone
    #       cd $(mktemp -d) && git clone https://github.com/aria2/aria2
    #       # Mark Safe
    #       git config --global --add safe.directory $(pwd)        
    #       # Build
    #       cd ./aria2 && sudo autoreconf -i && sudo ./configure --without-gnutls ARIA2_STATIC=yes && sudo make -j$(($(nproc)+1))
    #       # Strip & Move
    #       sudo strip "./src/aria2c" && sudo chmod +xwr "./src/aria2c"
    #       sudo cp "./src/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_x86_64_Linux"    
    #       # Remove tmp files
    #       #rm -rf /tmp >/dev/null 2>&1        
    #     continue-on-error: true
        
     #docker run --privileged -v $(pwd):/work dockcross/linux-arm64 bash -c "sudo apt install '*ares*' autoconf automake autopoint autotools-dev gettext '*gnutls*' libc-ares-dev libcppunit-dev libexpat1-dev libgcrypt-dev libgmp-dev libgpg-error-dev libsqlite3-dev libssh2-1-dev '*libssl*' libunistring-dev libtool libxml2-dev openssl nettle-dev '*p11-kit*' pkg-config python3-pip zlib1g-dev -y --ignore-missing --no-install-recommends ; pip3 install sphinx ; cd ./aria2 && make clean && autoreconf -i && ./configure --host=aarch64-linux-gnu ARIA2_STATIC=yes && make -j$(($(nproc)+1)) ; echo -e '----------------' ; sudo chmod +xwr ./src/aria2c && ./src/aria2c --version "
     
     #Fetch
      - name: Fetch aria2 bins [ Stable ]
        run: |
          #Android
          #aarch_arm
          curl -qflSL "https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/master/aria2/aria2c.bin-arm" -o  "$GITHUB_WORKSPACE/main/aria2/aria2c_aarch_arm_Android"
          #aarch64_arm64
          curl -qflSL "https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/master/aria2/aria2c.bin-arm64" -o  "$GITHUB_WORKSPACE/main/aria2/aria2c_aarch64_arm64_Android"
          #x86
          curl -qflSL "https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/master/aria2/aria2c.bin-x86" -o  "$GITHUB_WORKSPACE/main/aria2/aria2c_x86_Android"
          #x86_64
          curl -qflSL "https://raw.githubusercontent.com/Zackptg5/Cross-Compiled-Binaries-Android/master/aria2/aria2c.bin-x64" -o  "$GITHUB_WORKSPACE/main/aria2/aria2c_x86_64_Android"
          #Linux
          cd $(mktemp -d)
          for url in $(curl -s "https://api.github.com/repos/abcfy2/aria2-static-build/releases/latest" | jq -r '.assets[].browser_download_url'); do curl -LOJ "$url"; done
          for url in $(curl -s "https://api.github.com/repos/minnyres/aria2-windows-arm64/releases/latest" | jq -r '.assets[].browser_download_url'); do curl -LOJ "$url"; done
          find . -type f -name '*.zip*' -exec unzip -j -o {} -d {}_unzipped \;
          #aarch64_arm64
          mv "./aria2-aarch64-linux-musl_static.zip_unzipped/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_aarch64_arm64_musl_Linux"
          mv "./aria2-aarch64-linux-musl_libressl_static.zip_unzipped/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_aarch64_arm64_libressl_musl_Linux"
          #amd_x86_64
          mv "./aria2-x86_64-linux-musl_static.zip_unzipped/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_amd_x86_64_musl_Linux"
          mv "./aria2-x86_64-linux-musl_libressl_static.zip_unzipped/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_amd_x86_64_libressl_musl_Linux"          
          #arm_abi
          mv "./aria2-arm-linux-musleabi_static.zip_unzipped/aria2c/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_arm_abi_musl_Linux" 
          mv "./aria2-arm-linux-musleabi_libressl_static.zip_unzipped/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_arm_abi_libressl_musl_Linux"
          #mips 
          mv "./aria2-mips-linux-musl_static.zip_unzipped/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_mips_musl_Linux"
          mv "./aria2-mips-linux-musl_libressl_static.zip_unzipped/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_mips_libressl_musl_Linux"
          #mipsel  
          mv "./aria2-mipsel-linux-musl_static.zip_unzipped/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_mipsel_musl_Linux"
          mv "./aria2-mipsel-linux-musl_libressl_static.zip_unzipped/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_mipsel_libressl_musl_Linux"
          #mips64  
          mv "./aria2-mips64-linux-musl_static.zip_unzipped/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_mips64_musl_Linux"
          mv "./aria2-mips64-linux-musl_libressl_static.zip_unzipped/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_mip64_libressl_musl_Linux"
          #Windows
          mv "./aria2_1.36.0_arm64.zip_unzipped/aria2c.exe" "$GITHUB_WORKSPACE/main/aria2/aria2c_aarch64_arm64_Windows.exe" 
          mv "./aria2-x86_64-w64-mingw32_static.zip_unzipped/aria2c.exe" "$GITHUB_WORKSPACE/main/aria2/aria2c_amd_x86_x64_Windows.exe"
          mv "./aria2-i686-w64-mingw32_static.zip_unzipped/aria2c.exe" "$GITHUB_WORKSPACE/main/aria2/aria2c_i686_Windows.exe"
        continue-on-error: true
        
      - name: Fetch aria2 bins [ Latest ]
        run: |
          cd $(mktemp -d)
          for url in $(curl -s "https://api.github.com/repos/abcfy2/aria2-static-build/releases/latest" | jq -r '.assets[].browser_download_url'); do curl -LOJ "$url"; done
          find . -type f -name '*.zip*' -exec unzip -j -o {} -d {}_unzipped \;
          #aarch64_arm64
          mv "./aria2-aarch64-linux-musl_static.zip_unzipped/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_aarch64_arm64_musl_latest_Linux"
          mv "./aria2-aarch64-linux-musl_libressl_static.zip_unzipped/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_aarch64_arm64_libressl_musl_latest_Linux"
          #amd_x86_64
          mv "./aria2-x86_64-linux-musl_static.zip_unzipped/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_amd_x86_64_musl_latest_Linux"
          mv "./aria2-x86_64-linux-musl_libressl_static.zip_unzipped/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_amd_x86_64_libressl_musl_latest_Linux"          
          #arm_abi
          mv "./aria2-arm-linux-musleabi_static.zip_unzipped/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_arm_abi_musl_latest_Linux" 
          mv "./aria2-arm-linux-musleabi_libressl_static.zip_unzipped/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_arm_abi_libressl_musl_latest_Linux"
          #mips 
          mv "./aria2-mips-linux-musl_static.zip_unzipped/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_mips_musl_latest_Linux"
          mv "./aria2-mips-linux-musl_libressl_static.zip_unzipped/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_mips_libressl_musl_latest_Linux"
          #mipsel  
          mv "./aria2-mipsel-linux-musl_static.zip_unzipped/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_mipsel_musl_Linux"
          mv "./aria2-mipsel-linux-musl_libressl_static.zip_unzipped/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_mipsel_libressl_musl_latest_Linux"
          #mips64  
          mv "./aria2-mips64-linux-musl_static.zip_unzipped/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_mips64_musl_Linux"
          mv "./aria2-mips64-linux-musl_libressl_static.zip_unzipped/aria2c" "$GITHUB_WORKSPACE/main/aria2/aria2c_mip64_libressl_musl_latest_Linux"
          #Windows
          mv "./aria2-i686-w64-mingw32_static.zip_unzipped/aria2c.exe" "$GITHUB_WORKSPACE/main/aria2/aria2c_i686_latest_Windows.exe"
          mv "./aria2-x86_64-w64-mingw32_static.zip_unzipped/aria2c.exe" "$GITHUB_WORKSPACE/main/aria2/aria2c_amd_x86_x64_latest_Windows.exe"                    
        continue-on-error: true
        
      - name: Update README.md
        run: |  
           cd "$GITHUB_WORKSPACE/main"
           cat ./aria2/INFO.md > ./aria2/README.md
           echo -e "" >> ./aria2/README.md 
           echo '---' >> ./aria2/README.md
           echo '```console' >> ./aria2/README.md
           /bin/bash -c 'PS4="$ "; set -x; file ./aria2/aria2*' &>> ./aria2/README.md
           echo -e "" >> ./aria2/README.md
           echo -e "--> SHA256SUM" >> ./aria2/README.md
           /bin/bash -c 'PS4="$ "; set -x; sha256sum ./aria2/aria2*' &>> ./aria2/README.md   
           echo -e '```\n' >> ./aria2/README.md
           echo -e "" >> ./aria2/README.md
           echo '---' >> ./aria2/README.md
           echo -e "" >> ./aria2/README.md
           echo '- #### Sizes' >> ./aria2/README.md 
           echo -e "" >> ./aria2/README.md
           echo '```console' >> ./aria2/README.md       
           /bin/bash -c 'PS4="$ ";ls -lh ./aria2 | awk "{print \$5, \$9}" | column -t' &>> ./aria2/README.md
           echo '```' >> ./aria2/README.md     
           echo -e "" >> ./aria2/README.md 
           echo '---' >> ./aria2/README.md 
           echo -e "" >> ./aria2/README.md 
           echo '- #### Flags' >> ./aria2/README.md 
           echo '```console' >> ./aria2/README.md 
           /bin/bash -c 'PS4="$ "; set -x; qemu-aarch64-static aria2c_aarch64_arm64_libressl_musl_latest_Linux --version' &>> ./aria2/README.md 
           echo -e "" >> ./aria2/README.md 
           echo '```' >> ./aria2/README.md 
           echo -e "" >> ./aria2/README.md        
           echo '---' >> ./aria2/README.md 
           echo -e "" >> ./aria2/README.md 
        working-directory: main
        continue-on-error: true
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: ./main        
          commit_user_name: Azathothas # defaults to "github-actions[bot]"
          commit_user_email: AjamX101@gmail.com # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_message: Build || Fetch aria2 Binaries 
          #push_options: '--force'
