name: Fetch Curl Binaries

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22 * * 6"  # 10:00 PM UTC Every Saturday --> 03:45 AM Nepal Time Every Sunday
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:        
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: main
      - name: Install build dependencies
        run: "\
          sudo apt-get update\n
          sudo apt-get install -y --no-install-recommends bison build-essential ca-certificates flex file pkg-config qemu-system qemu-user qemu-user-static wget \n"      
          
      - name: Setup ENV
        run: |
          # Create Output Dir
          mkdir -p "$GITHUB_WORKSPACE/main/curl"
     
     #@latest_Linux: https://github.com/moparisthebest/static-curl/releases/latest
     #@latest_Windows: https://curl.se/windows/
      - name: Download @Latest Releases    
        run: |
         #Download
         #DOS
          set -x; curl -qflSL "http://mik.dyndns.pro/dos-stuff/bin/curl.exe" -o  "$GITHUB_WORKSPACE/main/curl/curl_DOS"
          set -x; curl -qflSL "http://mik.dyndns.pro/dos-stuff/bin/curllite.exe" -o  "$GITHUB_WORKSPACE/main/curl/curl_lite_DOS"
          set -x; curl -qflSL "http://mik.dyndns.pro/dos-stuff/bin/curltiny.exe" -o  "$GITHUB_WORKSPACE/main/curl/curl_tiny_DOS"
         #Linux
         #aarch64_arm64
          set -x; curl -qflSL "https://github.com/moparisthebest/static-curl/releases/latest/download/curl-aarch64" -o "$GITHUB_WORKSPACE/main/curl/curl_aarch64_arm64"
         #aarch64_arm64 HTTP3 
          set -x; curl -qflSL "https://github.com/stunnel/static-curl/releases/download/8.1.2/curl-static-amd64-8.1.2.tar.xz" -o "curl_aarch64_arm64_http3.tar.xz" &&  tar -xvf "curl_aarch64_arm64_http3.tar.xz" && mv "./curl" "$GITHUB_WORKSPACE/main/curl/curl_aarch64_arm64_http3"
         #amd64_x86_64 
          set -x; curl -qflSL "https://github.com/moparisthebest/static-curl/releases/latest/download/curl-amd64" -o "$GITHUB_WORKSPACE/main/curl/curl_amd64_x86_64"
         #amd64_x86_64 HTTP3  
          set -x; curl -qflSL "https://github.com/stunnel/static-curl/releases/download/8.1.2/curl-static-amd64-8.1.2.tar.xz" -o "curl_amd64_x86_64_http3.tar.xz" &&  tar -xvf "curl_amd64_x86_64_http3.tar.xz" && mv "./curl" "$GITHUB_WORKSPACE/main/curl/curl_amd64_x86_64_http3"      
         #armv7 
          set -x; curl -qflSL "https://github.com/moparisthebest/static-curl/releases/latest/download/curl-armv7" -o "$GITHUB_WORKSPACE/main/curl/curl_armv7"
         #armhf 
          set -x; curl -qflSL "https://github.com/moparisthebest/static-curl/releases/latest/download/curl-armhf" -o "$GITHUB_WORKSPACE/main/curl/curl_armhf"
         #i386 
          set -x; curl -qflSL "https://github.com/moparisthebest/static-curl/releases/latest/download/curl-i386" -o "$GITHUB_WORKSPACE/main/curl/curl_i386"
         #ppc64le 
          set -x; curl -qflSL "https://github.com/moparisthebest/static-curl/releases/latest/download/curl-ppc64le" -o "$GITHUB_WORKSPACE/main/curl/curl_ppc64le_powerpc64le"
         #Windows 
         #Windows 32-bit
          set -x; curl -qflSL "https://curl.se/windows/latest.cgi?p=win32-mingw.zip" -o win32.zip && unzip -j -o win32.zip -d win32 && cp "./win32/curl.exe" "$GITHUB_WORKSPACE/main/curl/curl_windows_amd_x86.exe"
         #Windows x86_64_amd64 
          set -x; curl -qflSL "https://curl.se/windows/latest.cgi?p=win64-mingw.zip" -o win64.zip && unzip -j -o win64.zip -d win64 && cp "./win64/curl.exe" "$GITHUB_WORKSPACE/main/curl/curl_windows_amd_x86_64.exe"
         #Windows arm64 
          set -x; curl -qflSL "https://curl.se/windows/latest.cgi?p=win64a-mingw.zip" -o win64arm.zip && unzip -j -o win64arm.zip -d win64arm && cp "./win64arm/curl.exe" "$GITHUB_WORKSPACE/main/curl/curl_windows_arm_x64.exe" 
         #Change Perms
          sudo chmod +xwr $GITHUB_WORKSPACE/main/curl/curl_* ; set +x
        continue-on-error: true
        
        
      - name: Update README.md
        run: |  
           cd "$GITHUB_WORKSPACE/main"
           cat ./curl/INFO.md > ./curl/README.md
           echo -e "" >> ./curl/README.md 
           echo '---' >> ./curl/README.md
           echo '```console' >> ./curl/README.md
           /bin/bash -c 'PS4="$ "; set -x; file ./curl/curl_*' &>> ./curl/README.md
           echo -e "" >> ./curl/README.md
           echo -e "--> SHA256SUM" >> ./curl/README.md
           /bin/bash -c 'PS4="$ "; set -x; sha256sum ./curl/curl_*' &>> ./curl/README.md   
           echo -e '```\n' >> ./curl/README.md
           echo -e "" >> ./curl/README.md
           echo '---' >> ./curl/README.md
           echo '- #### Version' >> ./curl/README.md
           echo '```console' >> ./curl/README.md
           /bin/bash -c 'PS4="$ "; set -x; qemu-aarch64-static ./curl/curl_aarch64_arm64 -V' &>> ./curl/README.md
           echo -e "" >> ./curl/README.md
           /bin/bash -c 'PS4="$ "; set -x; qemu-aarch64-static ./curl/curl_aarch64_arm64_http3 -V' &>> ./curl/README.md 
           echo '```' >> ./curl/README.md
           echo '---' >> ./curl/README.md
           echo -e "" >> ./curl/README.md                    
        working-directory: main
        continue-on-error: true
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: ./main        
          commit_user_name: Azathothas # defaults to "github-actions[bot]"
          commit_user_email: AjamX101@gmail.com # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_message: Fetch latest Curl Bins
          #push_options: '--force'
