# Fork: https://github.com/shutingrz/busybox-static-binaries-fat/tree/main
name: Quick Build Test

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: "${{ secrets.STATIC_BINARIES_RELEASER }}"

jobs:
  build:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          path: main
          
          
  #Create a new Release & Publish
      - name: Releaser
        uses: softprops/action-gh-release@latest
        with:
          body_path: "$GITHUB_WORKSPACE/main/tailscale/INFO.md"
          automatic_release_tag: 'latest'
          prerelease: false
          token: "${{ secrets.GITHUB_TOKEN }}"
          name: "Tailscale ${{ env.VERSION }}"
          tag_name: "tailscale"
          files: |
            $GITHUB_WORKSPACE/main/tailscale/*_Linux
            $GITHUB_WORKSPACE/main/tailscale/*_macOS
            $GITHUB_WORKSPACE/main/tailscale/*.exe
