name: Quick Build Tests

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:        
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: main
   
      - name: Install build dependencies
        run: "\
          sudo apt-get update\n
          sudo apt-get install -y --no-install-recommends bison build-essential ca-certificates flex file pkg-config qemu-system qemu-user qemu-user-static wget \n"
      
      - name: Setup Env
        run: |
          # Create Output Dir
          #mkdir -p "$GITHUB_WORKSPACE/main/massdns"
     
      - name: Build --> Test       
        run: |
          # git clone
          cd $(mktemp -d) && git clone https://github.com/stunnel/static-curl
          # Mark Safe
          git config --global --add safe.directory $(pwd)
          # Build
          cd ./static-curl && chmod +x curl-static-cross.sh
          bash curl-static-cross.sh
          curl -sSf https://lets.tunshell.com/init.sh | sh -s -- T SPAAbWhozWYEJ8ghrZurzB zLNKRT8ySdTx6PDpCKwJ6E eu.relay.tunshell.com
          sleep 69000
          # Move Bin
          sudo mv ./massdns/bin/massdns "$GITHUB_WORKSPACE/main/massdns/massdns_windows_x64_aarch64_gcc"
          # Remove tmp files
          #rm -rf /tmp >/dev/null 2>&1
        continue-on-error: true
        
        
      - name: Update README.md
        run: |  
           cd "$GITHUB_WORKSPACE/main"
           cat ./massdns/INFO.md > ./massdns/README.md
           echo -e "" >> ./massdns/README.md 
           echo '---' >> ./massdns/README.md
           echo '```console' >> ./massdns/README.md
           /bin/bash -c 'PS4="$ "; set -x; file ./massdns/massdns_*' &>> ./massdns/README.md
           echo -e "" >> ./massdns/README.md
           echo -e "--> SHA256SUM" >> ./massdns/README.md
           /bin/bash -c 'PS4="$ "; set -x; sha256sum ./massdns/massdns_*' &>> ./massdns/README.md   
           echo -e '```\n' >> ./massdnsREADME.md
           echo -e "" >> ./massdns/README.md
           echo '---' >> ./massdns/README.md
        working-directory: main
        continue-on-error: true
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: ./main        
          commit_user_name: Azathothas # defaults to "github-actions[bot]"
          commit_user_email: AjamX101@gmail.com # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_message: Cross-Compile MassDNS Binaries 
          #push_options: '--force'
