name: Quick Build Tests

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:        
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: main
   
      - name: Install build dependencies
        run: "\
          sudo apt-get update\n
          sudo apt-get install -y --no-install-recommends bison build-essential ca-certificates flex file pkg-config qemu-system qemu-user qemu-user-static wget \n"
      
      - name: Setup Env
        run: |
          # Create Output Dir
          #mkdir -p "$GITHUB_WORKSPACE/main/massdns"

        
      - name: Update README.md
        run: |  
           cd "$GITHUB_WORKSPACE/main"
           echo '---' >> ./wget/README.md
           echo '- #### Sizes' >> ./wget/README.md
           echo '```console' >> ./wget/README.md
           /bin/bash -c 'PS4="$ "; set -x; ls -lh ./wget | awk "{print \$5, \$9}" | column -t' &>> ./wget/README.md
           echo -e "" >> ./wget/README.md
           echo '```' >> ./wget/README.md           
           echo -e "" >> ./wget/README.md             
        working-directory: main
        continue-on-error: true
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: ./main        
          commit_user_name: Azathothas # defaults to "github-actions[bot]"
          commit_user_email: AjamX101@gmail.com # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_message: Quick Test
          #push_options: '--force'
